
i = 1
import os
def lor():

    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::") 
    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::''''''''''''''''''''::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::                        ::::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print("::::::::::                          :::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print("::::::::::                           ::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::                          ::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::                           :::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::                           ::::::::::::::::::::::::::       ::::::::::::::::::")
    print("::::::::::                            :::::::::::::::::::::::::          ::::::::::::::::")
    print(":::::::::::                           ::::::::::::::::::::::::::          :::::::::::::::")
    print("::::::::::::                         :::::::::::::::::::::::::::            :::::::::::::")
    print("::::::::::::                         :::::::::::::::::::::::::::          :::::::::::::::")
    print("::::::::::::                         ::::::::::::::::::::::::::::           :::::::::::::")
    print(":::::::::::::                         ::::::::::::::::::::::::::         ::::::::::::::::")
    print(":::::::::::::                      :::::::::::::::::::::::::::            :::::::::::::::")
    print("::::::::::::::                    ::::::::::::::::::::::::::                :::::::::::::")
    print(" ..         .    .         .   .                     .   .          .   .         .")
    print("  .  .            .   .             ..     .          .    .           .    .")
    print("   .     .             .   .                 .         .          .               . .   .")
    print(".                      .               .  .          . .        .  .     .  .         .")
def die():
    print("  _   _                  _   _")
    print(" ( ''' )                ( ''' )")
    print("   \   \                /   /")
    print("    \   \ @@@@@@@@@@@@@/   /")
    print("     \   @@@@@@@@@@@@@@@@@@@")
    print("    @@@@@@@@@@@@@@@@@@@@@@@@@")
    print("   @@@@@@@  @@@@@@@@@@@  @@@@@@")
    print(" @@@@@@@@    @@@@@@@@     @@@@@@@")
    print("@@@@@@@@@@  @@@@@@@@@@@  @@@@@@@")
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print(" @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
    print("     @@@@@@@@@@@@@@@        @@@@")
    print("    /   /@@@@@@@@@@@@@@@@@@@@@@@")
    print("   /   /      @@@@@@@@@@@@@@@@@")
    print("  /   /                    \   \ ")
    print("(     )                     \   \ ")
    print(" --¨--                      (     )")
    print("                             --¨--")
def kill():
    print(" ")
    print("    /\                                         ")  
    print("   (__)     o                                ")
    print("  -|  |----/                                     ")
    print(" | |  |   /                          ____     ____")
    print("  /   |                        |____/ '   \  /. x )    ")    
    print(" /_____\                      |____/_______ (____/     ")        
    print("")
def clear():
    os.system('cls' if os.name=='nt' else 'clear')
def monster():
    print("")
    print("     ________________ ")
    print("    |                |")
    print("    |     (  o  )    |")
    print("    |                |    ____")
    print("    \     _--_     /     /    \ ")
    print("      \          /      |      |")
    print("        ¨¨¨¨¨¨¨¨        |      |")
    print("        /      \         \    /")
    print("      /          \--------|  |")
    print("    |            |--------| |")
    print("   |              |        ||")
    print("   |       .      |    ")
    print("    |___________ |")
    print("    |           |")
    print("    |    /\      |")
    print("   |    |  |     |")
    print("  ======    ========")
def lake():
    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ")
    print(":::::::::::''':::::::::::::::::::::::::::::::::::::::::::: ")
    print("::::::::::     ::::::::::::::::::::::::::::::::::::::::::: ")
    print(":::::::::       :::::::::::::::::::::::::::::::::::::::::: ")
    print("           .            ___________ ")
    print("         .    ---------             ----------- ")
    print("      . .     /                                 \ ")
    print("     .     /              ~                      \ ")
    print("    .  .  /                        ~~~              \ ")
    print("   .     |         ~~~                              | ")
    print("   . .       \                                    __/ ")
    print("    .   . .      \                ~~~~          / ")
    print("     .  .         __                       __ ")
    print("     .    .           __________________/ ")
    print("           .         ")
    print("        .            ")
    print("                 .   ")
def bird():
    print("                            ________                                     ")
    print("                           / () ()  \                                    ")
    print("                         _/_         \                                  ")
    print("                          __\         -----\                           ")
    print("                            \        -      -\                          ")
    print("                             \_____   ''     -\                        ")
    print("                             |     \_____-----<                       ")
    print("                            |          |                               ")
    print("                    :::::::::::::::   |                               ")
    print("             ::::::::::::::::::::::::::::                .....::..")
    print("          ::::::::::::::::::::::::::::::::::        ::::::::::::::::")
    print("        :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ")
def win():
    print("    ")
    print("             o                                    ")
    print("         \  / \  /                              ")
    print("          \(   )/             _____              ")
    print("           \| |/             / x  x \           ")
    print("            | |             <        \        ")
    print("           /   \             \        \_____          ")
    print("          /_____\              \            ->              ")
    print("    :::::::::::::::::.... 3______\___        -<           ")
    print("..::::::::::::::::::::::::::.....3___\________<           ")
    print("::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
def home():
    print("                              .. .  ..             ")
    print("                             .  .  .               ")
    print("                             . .                   ")
    print("                            ..                     ")
    print("                     ––––––| |--                   ")
    print("                   /             \                 ")
    print("                 /_________________\               ")
    print("                  |    _           |                ")
    print("                 |    |_|   _      |                  ")
    print("                 |         | |    |                 ")
    print("           _____|__________|_|____|__             ")
    print("_____------                          -------___   ")

clear()
print("Give me your name")
name = input("my name is: ")
clear()
print("choose your weapon")
print("    /\        _  ")
print("    ||       / \ ")
print("    ||       \ / ")
print("    ||       ||  ")
print("   >--<      //  ")
print("    ||      ||   ")
print("    --      --   ")
print("")
print("1. sword")
print("2. staff")
ase = int(input())
clear()
if ase == 1:
    ase2 = "sword"
elif ase == 2:
    ase2 = "staff"
else:
    print("you chose wrong you die")
    die()
    quit()
print("Welcome to the cave")
print("")
print("")
print("")
print("                                                                                     \           /")
print("    :::::::::::::::::::::::::::::::::::                                                  _-----_")
print("::::::::::::::::::::::::::::::::::::::::::::                                            /       \ ")
print(":::::::::::::::::::::::::::::::::::::::::::::::::::::::                           _    |         |   -")
print(":::::::::::::''''''''''''''''''''::::::::::::::::::::::::::                             \       /")
print(":::::::::::                        :::::::::::::::::::::::::::::::::                     ¨-----¨")
print("::::::::::                          :::::::::::::::::::::::::::::::::::               /            \ ")
print("::::::::::                           :::::::::::::::::::::::::::::::::::::")
print(":::::::::::                          ::::::::::::::::::::::::::::::::::::::::")
print(":::::::::::                           ::::::::::::::::::::::::::::::::::::::::")
print(":::::::::::                           ::::::::::::::::::::::::::::::::::::::::")
print("::::::::::                            :::::::::::::::::::::::::::::::::::::::::")
print(":::::::::::                           ::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::                         :::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::                         :::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::                         :::::::::::::::::::::::::::::::::::::::::::")
print(":::::::::::::                         :::::::::::::::::::::::::::::::::::::::::::")
print(":::::::::::::                      :::::::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::::                    ::::::::::::::::::::::::::::::::::::::::::::::::::______________________")
print(",  ,        ,     -     -   -   -  - -                   .                .                 .")
print("                --     -   -  - -- -                  _.")
print("    .          - - -- -    -  - --                   .<o>           .                             .")
print("                - - --   -   -   - --                 /'                       .       .")
print(".     .          -  - - -----  - - -- --             |")
print("                    - - -- - - -- -- - - --     .                    .")
print("    .         .      --- ------- - - --------")
print("go in?")
print("1. no")
print("2. yes")
yes = int(input())
clear()
if yes == 2:
    print("")
else:
    print("you went home")
    home()
    quit() 

while i < 4:
    print("choose your direction")
    print("")
    print("")
    lor()
    print("1. left")
    print("2. right")
    suunta = int(input())
    clear()
    if suunta == 2:
        print("you went right there is a monster there do you want to fight?")
        monster()
        print("1. no")
        print("2. yes")
        valinta = int(input())
        clear()
        if valinta == 2:
            print("you attack the monster with " + ase2 + " dealing damage")
            if ase == 1:
                print("the monster bashes your skull and you die")
                die()
                quit()
            else:
                print("you succesfully kill the monster from long range")
                print("you realize that the path behind it goes nowhere. you go back")
                kill()
            
    elif suunta == 1:
        print("you went left")
        i += 5 
    else:
        print("you chose wrong you die")
        die()
        quit()
o = 1
while o < 4:
    print("You come across a big pond of water what do you wish to do?")
    lake()
    print("1. swim across")
    print("2. walk around")
    v2 = int(input())
    clear()         
    if v2 == 1:
        print("something grabs you and brings you deeper underground")
        print("you awaken WET in a dark cave")
        print("where do you wish to go?")
        lor()
        print("1. left")
        print("2. right")
        suunta = int(input())
        clear()
        if suunta == 2:
            print("the cave deepens")
            print("where do you wish to go?")
            lor()
            print("1. left")
            print("2. right")
            suunta = int(input())
            clear()
            if suunta == 2:
                print("the cave deepens...")
                lor()
                print("where do you wish to go?")
                print("1. left")
                print("2. right")
                suunta = int(input())
                clear()
                if suunta == 2: 
                    print("you made it out of the hole you were dragged into")
                    o += 5
                elif suunta == 1:
                    print("you went onwards and never found exit you died.")
                    die()
                    quit()
                else:
                    print("you chose wrong you die")
                    die()
                    quit()
            elif suunta == 1:
                print("you went onwards and never found exit you died")
                die()
                quit()
            else:
                print("you chose wrong you died")
                die()
                quit()
        elif suunta == 1:
            print("you continued on your tracks forever and ended up dead")
            die()
            quit()
        else:
            die()
            print("you chose wrong you died")
            quit()
    elif v2 == 2:
        print("you walked around it and nothing happened")
        print("you find a tunnel that goes deeper")
        print("you enter it")
        o += 5
    else:
        print("you chose wrong you died")
        die()
        quit()
            
print("you enter a grand space that beholds piles upon piles of gold")
print("theres a dragon guarding the gold")
bird()
print("do you wish to defeat it?")
print("1. no")
print("2. yes")
decision = int(input())
clear()
if decision == 1:
    print("you go back home and make bread water soup")
    print("your spouse is disappointed in you, " + name + " are you proud of yourself?")
    print("youre poor")
    home()
    print("thank you for playing")
    quit()
elif decision == 2:
    print("you try taking the dragon head on")
    print("the dragon breathes fire upon you")
    if v2 == 1:
        print("the wet clothes from before save you from certain death")
        print("you manage to slay the dragon with your " + ase2 + " congratulations")
        print("you return home and your spouse waits there for you happily")
        print("you eat like a king for the rest of your life")
        win()
        print("thank you for playing ", name)
        input()
    else:
        print("the dragons fires kill you instantly")
        print("you will never see your family again")
        die()
        print("goodbye")
        quit()
else:
    print("you chose wrong you lost the game")
    die()
    quit()


